name: Daily YouTube Automator
on:
  schedule:
    - cron: '0 13,23 * * *' # Runs twice a day
  workflow_dispatch: # Allows manual start

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          sudo apt-get install ffmpeg
          pip install -r requirements.txt
      - name: Run Automator
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python app.py
